---
title: "consults"
author: "Tim Dennis"
date: "11/19/2019"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(lubridate)
library(kableExtra)
consults <- read_csv('data/calendly-events-export-2017-2019.csv')
consults <- clean_names(consults)
```

## DSC Consultations


```{r}
consults %>% 
  count(user_name, sort = TRUE) %>% 
  group_by()
```

```{r}
consults <- consults %>% 
  mutate(start_date_time2 = ymd_hm(start_date_time))
```


```{r}
consults %>% 
  group_by(month=floor_date(start_date_time2, "month")) %>% 
  summarize(consults = sum(n())) %>% 
  ggplot(aes(month, consults)) + geom_line()
```

```{r}
consults %>% 
  group_by(year=year(start_date_time2)) %>% 
  summarize(consults = sum(n())) %>% 
  ggplot(aes(year, consults)) + geom_col()
```

```{r}
consults %>% 
  group_by(year=year(start_date_time2)) %>% 
  summarize(consults = sum(n())) %>% 
  kable() %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```